baseURL = 'http://mainstreettapandgrill.com/'
languageCode = 'en-us'
title = 'MST&G'
theme = 'hugo-book'
sectionPagesMenu = 'main'

[params]
BookSection = 'posts'
BookMenuBundle = '/menu'

[markup]
[markup.goldmark.renderer]
    unsafe = true

[markup.tableOfContents]
  startLevel = 1